spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_DB_ENDPOINT:jdbc:postgresql://localhost:5432/smartchoice}
    username: ${POSTGRES_DB_ENDPOINT_USER:tan}
    password: ${POSTGRES_DB_ENDPOINT_PASS:tandb}
    tomcat:
      max-wait: 20000
      max-active: 50
      max-idle: 20
      min-idle: 15
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    self-config:
      max-attempts: ${RABBITMQ_MAX_ATTEMPTS:3}

server:
  port: ${SERVER_PORT:9399}

logging:
  level:
    org:
      hibernate:
        SQL: INFO
